Conclusion of run_validation method.

diff --git a/Pre-commit/pre-commit-eslint-phpcs b/Pre-commit/pre-commit-eslint-phpcs
--- a/Pre-commit/pre-commit-eslint-phpcs
+++ b/Pre-commit/pre-commit-eslint-phpcs
@@ -23,100 +23,6 @@ STAGED_VUE_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".vue\
 PASS=true
 INSTALL=1
 
-# if [ "$STAGED_PHP_FILES" = "" ] & [ "$STAGED_JS_FILES" = "" ]; then
-#   echo -e "No PHP or JS files to be commited. Preparing commit..."
-#   exit 0
-# fi
-
-# if [ "$STAGED_PHP_FILES" = "" ]; then
-#   echo -e "No PHP files to be commited."
-# else
-#   echo "Validating PHPCS..."
-
-#   for FILE in $STAGED_PHP_FILES; do
-#     vendor/bin/phpcs --standard=PSR12 "$FILE"
-
-#     if [[ "$?" != 0 ]]; then
-#       PASS=false
-#     fi
-#   done
-
-#   if ! $PASS; then
-#     # echo -e "${B_RED}PHPCS Failed!${NO_FORMAT}"
-#     # vendor/bin/phpcs $STAGED_FILES --report=summary
-#     echo -e "PHPCS validation: ${C_RED}✘${NO_FORMAT}"
-#   else
-#     echo -e "${C_GREEN}PHPCS Passed!${NO_FORMAT}"
-#   fi
-# fi
-
-# if [ "$STAGED_JS_FILES" = "" ]; then
-#   echo -e "No JS files to be commited."
-# else
-#   #//TODO Validate JS using ESLint
-#   echo ""
-# fi
-
-# if [ "$STAGED_VUE_FILES" = "" ]; then
-#   echo -e "No VUE files to be commited."
-# else
-#   #//TODO Validate Vue using ESLint
-#   echo ""
-# fi
-
-# which node &>/dev/null
-
-# if [[ "$?" == 1 ]]; then
-#   echo -e "NodeJS not installed ${C_RED}✘${NO_FORMAT}"
-#   INSTALL=0
-# else
-#   echo -e "NodeJS installed ${C_GREEN}✔${NO_FORMAT}"
-# fi
-
-# which npm &>/dev/null
-
-# if [[ "$?" == 1 ]]; then
-#   echo -e "NPM not installed ${C_RED}✘${NO_FORMAT}"
-#   INSTALL=0
-# else
-#   echo -e "NPM installed ${C_GREEN}✔${NO_FORMAT}"
-# fi
-
-# which npx eslint &>/dev/null
-
-# if [[ "$?" == 1 ]]; then
-#   echo -e "ESLint not installed ${C_RED}✘${NO_FORMAT}"
-#   INSTALL=0
-# else
-#   echo -e "ESLint installed ${C_GREEN}✔${NO_FORMAT}"
-# fi
-
-# if [[ $INSTALL == 0 ]]; then
-#   exit 0
-# fi
-
-# #//TODO Method to validate files
-
-# #//TODO Method to check instalation requirements
-
-# if ! $PASS; then
-#   echo -ne "Do you want to commit with errors? (${C_GREEN}y${NO_FORMAT}/${C_RED}n${NO_FORMAT}) "
-#   read answer
-
-#   while [[ "$answer" != "y" && "$answer" != "n" ]]; do
-#     echo -ne "Wrong input. try again. (${C_GREEN}y${NO_FORMAT}/${C_RED}n${NO_FORMAT}) "
-#     read answer
-#   done
-
-#   if [[ "$answer" == "y" ]]; then
-#     echo -e "${C_YELLOW}Commiting with errors...${NO_FORMAT}"
-#   else
-#     exit 1
-#   fi
-# fi
-
-# exit $?
-
 check_instalation() {
   # echo "$1 / $2"
   which $2 &>/dev/null
@@ -137,32 +43,30 @@ check_staged_files() {
 }
 
 run_validation() {
-  echo "run_validation()! To be done!"
-  #//TODO - run_validation
-  # if [ "$STAGED_PHP_FILES" = "" ]; then
-  #   echo -e "No PHP files to be commited."
-  # else
-  #   echo "Validating PHPCS..."
+  if [ "$1" = "" ]; then
+    echo -e "No $4 files to be validated by $3. Moving on..."
+  else
+    echo "Validating $3..."
 
-  #   for FILE in $STAGED_PHP_FILES; do
-  #     vendor/bin/phpcs --standard=PSR12 "$FILE"
+    for FILE in $1; do
+      $2 "$FILE"
 
-  #     if [[ "$?" != 0 ]]; then
-  #       PASS=false
-  #     fi
-  #   done
+      if [[ "$?" != 0 ]]; then
+        PASS=false
+      fi
+    done
 
-  #   if ! $PASS; then
-  #     # echo -e "${B_RED}PHPCS Failed!${NO_FORMAT}"
-  #     # vendor/bin/phpcs $STAGED_FILES --report=summary
-  #     echo -e "PHPCS validation: ${C_RED}✘${NO_FORMAT}"
-  #   else
-  #     echo -e "${C_GREEN}PHPCS Passed!${NO_FORMAT}"
-  #   fi
-  # fi
+    if ! $PASS; then
+      # echo -e "${B_RED}PHPCS Failed!${NO_FORMAT}"
+      # vendor/bin/phpcs $STAGED_FILES --report=summary
+      echo -e "$3 validation ($4): ${C_RED}✘${NO_FORMAT}"
+    else
+      echo -e "${C_GREEN}$3 Passed!${NO_FORMAT}"
+    fi
+  fi
 }
 
-check_instalation "Docker" "sdocker"
+check_instalation "Docker" "docker"
 
 if [[ "$?" != 1 ]]; then
   INSTALL=1
@@ -170,22 +74,19 @@ if [[ "$?" != 1 ]]; then
   check_instalation "NodeJS" "node" #Node
   check_instalation "NPM" "npm" #NPM
   check_instalation "ESLint" "npx eslint" #ESLint
-else
-  echo "Now validate the staged files! (PHP, JS, VUE)"
-  #//TODO Now validate the PHPCS and ESLint
 fi
 
-#Temp
+#Temp Strings
 if [[ $INSTALL == 0 ]]; then
   echo "Alguma coisa não foi instalada como deve de ser!"
   exit 1
 else
   echo "Tudo foi instalado com sucesso!"
+
+  run_validation "$STAGED_PHP_FILES" "vendor/bin/phpcs --standard=PSR12" "PHPCS" "PHP"
+  run_validation "$STAGED_JS_FILES" "npx eslint" "ESLint" "JS"
+  run_validation "$STAGED_VUE_FILES" "npx eslint" "ESLint" "Vue"
+
+  #//TODO Print all validation lines (Line 156) at the same time! (Use a array)
   exit 1
 fi
-
-exit 1  #Temp
-
-#run_validation "$STAGED_PHP_FILES" "PHPCS"
-#run_validation "$STAGED_JS_FILES" "ESLint"
-#run_validation "$STAGED_VUE_FILES" "ESLint"
