Replaced colors formatting with vars #3

diff --git a/Pre-push/pre-push-protect-master b/Pre-push/pre-push-protect-master
--- a/Pre-push/pre-push-protect-master
+++ b/Pre-push/pre-push-protect-master
@@ -4,6 +4,15 @@
 ## Protects master branch; allows merge commits into master; tells user how many commits are going to be pushed. ##
 ###################################################################################################################
 
+# Color vars
+C_GREEN="\033[32m"
+
+# Background vars
+B_RED="\033[41m"
+
+# Clear Format
+NO_FORMAT="\033[0m"
+
 protected_branch='master'
 current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
 commits_behind=$(git rev-list --count origin/$current_branch...@ | cut -f1)
@@ -31,18 +40,18 @@ while read local_ref local_sha remote_ref remote_sha; do
                         # Check for Merge commit
                         commit=$(git rev-list -n 1 --grep '^Merge' "$range")
                         if [ -n "$commit" ]; then
-                                echo >&2 "\t\033[32mPUSH STARTING:\033[0m Found 'Merge' commit in $local_ref, pushing..."
+                                echo >&2 "${C_GREEN}PUSH STARTING:${NO_FORMAT} Found 'Merge' commit in $local_ref, pushing..."
                                 exit 0
                         fi
                 else
                         if [ $commits_behind -eq 0 ]; then
-                                echo "\t\033[41mPUSH FAILED [$current_branch]:\033[0m There is nothing to push!"
+                                echo "${B_RED}PUSH FAILED [$current_branch]:${NO_FORMAT} There is nothing to push!"
                                 exit 1
                         else
                                 if [ $commits_behind -eq 1 ]; then
-                                        echo "\t\033[32mPUSH STARTING [$current_branch]:\033[0m You're about to push $commits_behind commit!"
+                                        echo "${C_GREEN}PUSH STARTING [$current_branch]:${NO_FORMAT} You're about to push $commits_behind commit!"
                                 else
-                                        echo "\t\033[32mPUSH STARTING [$current_branch]:\033[0m You're about to push $commits_behind commits!"
+                                        echo "${C_GREEN}PUSH STARTING [$current_branch]:${NO_FORMAT} You're about to push $commits_behind commits!"
                                 fi
                         fi
                 fi
